### ISSUE TITLE
(putty) Use full PuTTY installer instead of portable zip

### ISSUE THREAD

**Issue by cinderblock** [ferventcoder/chocolatey-packages#100]
PuTTY publishes an installer that does a few nice things that `putty.portable` doesn't:
- Registers .ppk files in Explorer
- Creates start menu entries
- Plays well with other software (Others have complained about exe shims causing issues)

One thing that the PuTTY installer does not do is add all of the executables to the path. For most of the executables, being in the path is not necessary as shell integration and the Start Menu are often easier to use. Some exes however, `pscp.exe` for one, are very handy to have in the Windows PATH.

Can we use the real PuTTY installer and add exe shims so that relevant executable are also in the path? (Or is adding PuTTY install dir to the path better?)

**Comment by ferventcoder** [comment]
To be fair, some of those shim complaints go back a while - most if not all of those complaints resulted in fixes.

**Comment by ferventcoder** [comment]
We should definitely do this - thought we already did though.

**Comment by pascalberger** [comment]
The current MSI installer seems to add the executable to the path.

See https://github.com/chocolatey/chocolatey-coreteampackages/pull/539 for switching to the MSI installer.

**Comment by gep13** [comment]
This package is now being maintained here:

https://github.com/chocolatey/chocolatey-coreteampackages

So going to close this out.
