### ISSUE TITLE
(skype) ensure download with checksum before proceeding to uninstall older version

### ISSUE THREAD

**Issue by ferventcoder** [ferventcoder/chocolatey-packages#102]
See https://chocolatey.org/packages/skype#comment-2404221279

**Comment by cpmcgrath** [comment]
This seems like a case that chocolatey could handle better with the helper functions.

The simplest implementation to me would split Install-ChocolateyPackage into two functions, and then have Install-ChocolateyPackage just call them sequentially.

Then in cases like skype where you need to do an uninstall you could write something like...

    $result = PrepareInstall-ChocolateyPackage $packageName $fileType $silentArgs $url
    # do uninstall or whatever 
    FinishInstall-ChocolateyPackage $result

**Comment by ferventcoder** [comment]
Actually there is already a split - Install-ChocolateyPackage is just Get-ChocolateyWebFile and Install-ChocolateyInstallPackage.

**Comment by gep13** [comment]
This package is now being maintained here:

https://github.com/chocolatey/chocolatey-coreteampackages

So going to close this out.
