### ISSUE TITLE
(adobereader) Adobe Reader page is out of date- should link to Update page to make it easy to discover how to get the latest version

### ISSUE THREAD

**Issue by jnm2** [ferventcoder/chocolatey-packages#112]
> Adobe is doing some weird stuff and we don't yet have compatibility with it so we are providing two packages. Not optimal, but a stop gap solution.

There should be a notice on the [Adobe Reader page](https://chocolatey.org/packages/adobereader) to redirect users to the [Adobe Reader Update page](https://chocolatey.org/packages/adobereader-update) in order to install an up-to-date version.

**Comment by ferventcoder** [comment]
Thanks!

**Comment by gep13** [comment]
This package is now being maintained over here:

https://github.com/aronovgj/choco-auto

So going to close this out.
