### ISSUE TITLE
(adobereader) Adobe Reader DC has 2 versions. Should perhaps have 2 packages (Classic and Continuous).

### ISSUE THREAD

**Issue by trekytech7** [ferventcoder/chocolatey-packages#117]
Are you considering creating two version in the future? (Classic and Continuous)
   http://www.adobe.com/devnet-docs/acrobatetk/tools/AdminGuide/whatsnewdc.html

Maintaining Reader in an Enterprise environment appears to be overly complicated... (http://www.adobe.com/devnet-docs/acrobatetk/index.html), (http://download.adobe.com/pub/adobe/) "Keep it simple, smart guy" :)

**Comment by michalzobec** [comment]
about updates of adobe reader dc - for updates you must have adobe id and distribution agreement - http://www.adobe.com/support/downloads/product.jsp?product=10&platform=Windows

**Comment by gep13** [comment]
This package is now being maintained over here:

https://github.com/aronovgj/choco-auto

So going to close this out.
