### ISSUE TITLE
Insecure mysql package

### ISSUE THREAD

**Issue by kwinteng** [ferventcoder/chocolatey-packages#128]
Hello,
Regarding your mysql package (mysql community server), is there a way to have the option --initialize-insecure instead of the normal one.
I understand your reasoning but I'd like it unsecure or if possible be able to give a root password as argument.

I'm having difficulties using the secure version and then being able to change the password in an automated install.
I tried running the ps1 script directly changing the initialize to initialize-insecure locally but it still seems to go and download your online script.
Hopefully you could assist me on that.

Kind regard,
Kwinten
IT Student @ College of Ghent, Belgium

**Comment by kwinteng** [comment]
My appologies, i did find out i was working with a wrong copy but it can't use the chocolatey commands in just powershell. So i'm still having the same issue as before

**Comment by ferventcoder** [comment]
No worries, It is just something we'll simply need to pass to the installer.

**Comment by ferventcoder** [comment]
Done.
