### ISSUE TITLE
v15.14 says installed successfully, can't find a trace

### ISSUE THREAD

**Issue by solvingJ** [ferventcoder/chocolatey-packages#131]
Windows 10
Could not find in add/remove programs
Could not find a 7zip folder in c:\program files\ or c:\program files (x86)
When double clicking a .7z file, windows doesnt have associated program. 
When browsing for a program, 7zip not listed
Uninstalled with choco successfully, reinstalled, no change. 
Reinstalled with choco install 7zip.install as well, same outcome
Please let me know if i can be of further assistance.

**Comment by ferventcoder** [comment]
Do me a favor `choco install 7zip --force --force-dependencies -dv`

and then post the results from the output log to here.

**Comment by FilipDeVos** [comment]
I had the same problem. Running with --force-dependencies fixed the issue. 

The snippet of the log that shows what was wrong.
```
Capturing package files in 'C:\ProgramData\chocolatey\lib\7zip'
 Found 'C:\ProgramData\chocolatey\lib\7zip\7zip.nupkg'
  with checksum '7FAC4A893610402D285F26DAC906A5AB'
[NuGet] Unable to locate dependency '7zip.install (= 15.14)'. It may have been uninstalled.
[NuGet] Uninstalling '7zip 15.14'.
[NuGet] Removed file '7zip.nupkg' to folder 'C:\ProgramData\chocolatey\lib\7zip'.
[NuGet] Removed folder 'C:\ProgramData\chocolatey\lib\7zip'.
[NuGet] Successfully uninstalled '7zip 15.14'.
```

I don't know why 7zip.install was not installed though.

**Comment by ferventcoder** [comment]
Calling this a possible issue with the community repository.
