### ISSUE TITLE
(virtualbox) Install 64bit *or* 32bit, and Extension Pack

### ISSUE THREAD

**Issue by onlytherain** [ferventcoder/chocolatey-packages#132]
There have been some comments/issues about installing VirtualBox (both 64bit and 32bit versions). The following is a procedure I have used previously to install VirtualBox manually [by extracting the (.msi) installer files from the downloaded package (.exe)]. I should imagine this can be transposed to a Chocolatey script methodology without too much difficulty.

You may need to find the stable download locations for both the package (.exe) and the extension (.vbox-entpack) files. Oracle's file naming conventions seem fairly consistent.

VIRTUALBOX

1) Extract files from container to custom folder in %TEMP%:
`$ %ChocolateyInstall%\temp\VirtualBoxInstall.exe --path .\ --extract`

2a) Install VirtualBox (64bit):
`$ start /wait msiexec.exe /i "%ChocolateyInstall%\temp\VirtualBox-5.0.16-r105871-MultiArch_amd64.msi" /qn /norestart ALLUSERS=1 VBOX_INSTALLDESKTOPSHORTCUT=1 VBOX_INSTALLQUICKLAUNCHSHORTCUT=1 /Log %TEMP%\VirtualBox.log`

2b) Install VirtualBox (32bit):
`$ start /wait msiexec.exe /i "%ChocolateyInstall%\temp\VirtualBox-5.0.16-r105871-MultiArch_x86.msi" /qn /norestart ALLUSERS=1 VBOX_INSTALLDESKTOPSHORTCUT=1 VBOX_INSTALLQUICKLAUNCHSHORTCUT=1 /Log %TEMP%\VirtualBox.log`

3) Install Extension Pack (in either 64bit or 32bit environment):
`$ "%ProgramFiles%\Oracle\VirtualBox\VBoxManage.exe" extpack install "%ChocolateyInstall%\temp\Oracle_VM_VirtualBox_Extension_Pack-5.0.16-105871.vbox-extpack"`

Hope this is useful.
Lee James

**Comment by ferventcoder** [comment]
Thanks! This all could easily be achieved. Do you foresee any issues with installing the extension pack? Rather are there folks that do not want this?

**Comment by onlytherain** [comment]
The only thing that comes to mind is possibly pinging the localhost (or similar) to delay extension pack installation a few seconds after VirtualBox has finished installing. Generally, I've experienced no issues though.

Something you should note is the difference in version structure between the msi installer and the extension pack — the msi installer has the 'r' immediately before the build number, whereas the extension pack doesn't. That could potentially save a few minutes of annoyance when using the $version variable.

**Comment by ferventcoder** [comment]
I'd typically expect that we'd search for the file name and use what is found or error.

**Comment by onlytherain** [comment]
Also, because the Extension pack seems to be always released with the new build, it might make sense to install that at the same time, rather than leave it to the user to forget about it and be forced to go to the next version.

**Comment by onlytherain** [comment]
And yes, that's the better way. The difference in naming did catch me out a while back though (just once).

**Comment by onlytherain** [comment]
I don't imagine many would not want the extension pack. Installing it to the system simply makes it available to use. It still needs to be manually applied to a virtual machine as needed.

VBoxManage.exe from the newly installed VirtualBox instance is used to install the extension pack — it's possible that elevated privileges are required to install it via commandline. I've never tried to execute the .vbox-extpack directly (via commandline).

**Comment by ferventcoder** [comment]
I asked because of this package - https://chocolatey.org/packages/VirtualBox.ExtensionPack 

Although it appears broken and can be deprecated.

**Comment by onlytherain** [comment]
Interesting. Naturally it depends on VBox already being installed, so maybe combining them both is best afterall. Why I say that is that I'm sure there are people who might try and install the extension pack first o.O

**Comment by onlytherain** [comment]
Food for thought...

Attempting to install VirtualBox 32bit on a Windows 64bit machine may not be advisable.

This is not verified, but seems possible.

Because VirtualBox also installs architecture-specific networking (and other) drivers, installing the 32bit version of VirtualBox on a 64bit platform may be disallowed, in which case, the %ProgramFiles% location is appropriate for both 64bit and 32bit platforms, respectively. Not %ProgramFiles(x86)%!

This is likely why the installer (.exe) extracts only the 64bit msi OR the 32bit version depending on architecture. An option to install the 32bit version is not even offered during setup (on 64bit).

If this is true, it would also explain the inability to run vboxmanage [it expects a %ProgramFiles% location rather than %ProgramFiles(x86)%]. Refer to Marcin Kłopotek's comment on the Chocolatey VirtualBox package page.

Is it possible an assumption was made that installing the 32bit version is OK, and it's really not?

**Comment by onlytherain** [comment]
It may be beneficial to re-word the Chocolatey VirtualBox package description a little, to avoid any possible confusion. The phrase "...a general-purpose full virtualizer for x86 hardware" suggests VirtualBox is for 'Intel x86 based hardware' — and it is — however, it may easily be mistaken for meaning it's 32bit/x86 (only).

**Comment by ferventcoder** [comment]
> It may be beneficial to re-word the Chocolatey VirtualBox package description a little, to avoid any possible confusion.

I generally agree, but that's not our wording. :+1: 

Unless they've updated it. Should we add a note at the end to explain that bit?

**Comment by onlytherain** [comment]
Once you have completed the Chocolatey VirtualBox package, a statement to the effect that it will install either the 64bit or 32bit application, depending on Windows architecture, should be enough.

**Comment by ferventcoder** [comment]
@majkinetor @admiringworm here is another, but maybe not valid anymore.

**Comment by majkinetor** [comment]
I will add extension pack by default.

> Because VirtualBox also installs architecture-specific networking (and other) drivers, installing the 32bit version of VirtualBox on a 64bit platform may be disallowed, in which case, the %ProgramFiles% location is appropriate for both 64bit and 32bit platforms, respectively. Not %ProgramFiles(x86)%!

I am not going to implement this. Its a serious issue and should be handled upstream.

**Comment by majkinetor** [comment]
@onlytherain if you want to participate, please visit chocolatey/chocolatey-coreteampackages#423.

**Comment by ferventcoder** [comment]
I think what is being stated here (hard to understand at first) is that the addition to path should look at program files instead of program files (x86) because it will always be programs files - really though, when we find the path from the uninstaller key in the registry that should be used.

**Comment by majkinetor** [comment]
Good, that is already fixed then - I don't use fixed paths in packages. `Get-AppInstallLocation` checks many places and will find the correct path.

**Comment by gep13** [comment]
This package is now being maintained here:

https://github.com/chocolatey/chocolatey-coreteampackages

So going to close this out.
