### ISSUE TITLE
(putty) Putty Installer is now MSI

### ISSUE THREAD

**Issue by ferventcoder** [ferventcoder/chocolatey-packages#133]
> Could you please consider to switch to the msi installer as suggested by the authors:
> "2016-03-10 Switching to MSI-format Windows installer
> 
> We're switching to the MSI format for PuTTY's Windows installer (generated by the WiX toolset).
> 
> Mostly this is because of the report late last year that Windows installers created by Inno Setup are vulnerable to being hijacked by particular DLLs left in the same directory (such as your browser downloads directory).
> 
> However, MSI also provides some other useful features, including automated silent install/uninstall via msiexec /q, and also the ability to automatically put the PuTTY install directory on the PATH so that Command Prompts can run PSCP without any fuss.
> 
> The development snapshots will now have MSI installers, and we have also retrospectively generated an MSI installer for the recent 0.67 release. Sorry we didn't have it ready in time – MSI is quite complicated if you're not an expert, and it took a long time to get it to work!
> 
> For the moment, we're still providing Inno Setup installers as well, in case anyone has trouble with our new and not-very-tested MSIs. But we recommend that people use the MSI if possible, and if you must use the Inno Setup installer, make sure to put it in an empty directory before running it."
> 
> http://www.chiark.greenend.org.uk/~sgtatham/putty/

**Comment by ferventcoder** [comment]
Chocolatey always puts the installers in an empty directory that it just created, so that is not an issue. However we may want to investigate switching over to MSI.

**Comment by pascalberger** [comment]
This would be fixed with https://github.com/chocolatey/chocolatey-coreteampackages/pull/539

**Comment by SBI-boy** [comment]
Now there is another issue, when you try to install putty.install only the 32 bit version is installed, the 64 bit version just doesn't exist in your repository

**Comment by pascalberger** [comment]
@SBI-boy Can you please create an issue for supporting 64-bit PuTTY install on https://github.com/chocolatey/chocolatey-coreteampackages, as the package is now maintained there.

**Comment by gep13** [comment]
@pascalberger @ferventcoder I am going to go ahead and close this issue out.
