### ISSUE TITLE
7z installer options

### ISSUE THREAD

**Issue by schmerold** [ferventcoder/chocolatey-packages#134]
When using Chocolatey, what is best way to specify these installer options:
/passive /norestart INSTALLDIR="c:\windows"

Not sure if this is correct place to ask this question, if not, let me know appropriate forum - thanks.

**Comment by ferventcoder** [comment]
@schmerold https://github.com/chocolatey/choco/wiki/CommandsInstall#options-and-switches is the place to look. What you are looking for is `-o --installargs = '"/passive /norestart INSTALLDIR=c:\whatever"'`

~~~
--ia, --installargs, --installarguments, --install-arguments=VALUE
  InstallArguments - Install Arguments to pass to the native installer
  in the package. Defaults to unspecified.

-o, --override, --overrideargs, --overridearguments,
--override-arguments
  OverrideArguments - Should install arguments be used exclusively
  without appending to current package passed arguments? Defaults to
  false.
~~~

If you need to pass quotes for those values - see https://github.com/chocolatey/choco/wiki/CommandsReference#how-to-pass-options--switches, there is a specific different way to do it depending on whether you are in cmd.exe or powershell.exe. Also, you can see all of these options when you run `choco -?` and `choco install -?`
