### ISSUE TITLE
Dropbox fails to install if the Username contains special characters.

### ISSUE THREAD

**Issue by theMaruja** [ferventcoder/chocolatey-packages#135]
https://github.com/ferventcoder/chocolatey-packages/blob/master/automatic/dropbox/tools/chocolateyInstall.ps1#L7

`choco install dropbox -y` fails if the username contains a special character. In my example it is a simple space -> " ". My test unsername is "E. Xample". Using this username and trying to `choco install dropbox` i receive the Error:

WARNING: Write-ChocolateyFailure is deprecated. If you are the package maintainer, please use 'throw $_.Exception'
 instead.
 An object at the specified path C:\Users\E622B~1.XAM does not exist.
 At C:\ProgramData\chocolatey\helpers\functions\Write-ChocolateyFailure.ps1:24 char:3
 +   throw "$failureMessage"
 +   ~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: (An object at th...does not exist.:String) [], RuntimeException
     + FullyQualifiedErrorId : An object at the specified path C:\Users\E622B~1.XAM does not exist.
The install of dropbox was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\dropbox\tools\chocolateyInstall.ps1'.
 See log for details.

and `C:\Users\E622B~1.XAM` is clearly not the used username.

**Comment by ferventcoder** [comment]
Upgrade to 0.9.10 beta. This is fixed -  https://github.com/chocolatey/choco/issues/532

https://github.com/chocolatey/choco/blob/master/CHANGELOG.md
