### ISSUE TITLE
(skype) Skype doesn't start with windows after upgrading through chocolatey

### ISSUE THREAD

**Issue by wizpig64** [ferventcoder/chocolatey-packages#139]
As much as I appreciate disabling "start skype with windows" as the default setting, it would be nice if upgrading through chocolatey respected my choice of turning it back on. Thanks.

**Comment by ferventcoder** [comment]
It's likely due to the way the package installs it - it's not the best behaved upgrading app when using the installer, so the package currently uninstalls and reinstalls it for upgrades.

**Comment by ferventcoder** [comment]
We'll just need some way of telling it not to remove settings.

**Comment by gep13** [comment]
This package is now being maintained here:

https://github.com/chocolatey/chocolatey-coreteampackages

So going to close this out.
