### ISSUE TITLE
Node.js 4.4.4 and 6.1.0

### ISSUE THREAD

**Issue by StefanScherer** [ferventcoder/chocolatey-packages#144]
Just a reminder. Node.js LTS 4.4.4 has been released.
As well the latest version switch from version 5 to 6 and there is a 6.1.0 release.
Probably the automatic packages need some care to generate new choco packages.

**Comment by ferventcoder** [comment]
Thanks!

**Comment by ferventcoder** [comment]
This is up. There was an issue with the auto packager. It's been resolved so everything is hunky dory again. 👍

**Comment by StefanScherer** [comment]
Thank you!!
