### ISSUE TITLE
(php) php.ini and extensions not working out of the box

### ISSUE THREAD

**Issue by cybtachyon** [ferventcoder/chocolatey-packages#145]
Since we're using `/tools` still for 7.0+, I believe we should be:
- Setting the Windows `PHPRC` env var to `FOLDERID_ProgramData\php` ('C:\ProgramData\php'.)
- Adding a default `php.ini` to that same folder.
- Setting the `php.ini` extension default to the correct folder `extension_dir = "C:\tools\php\ext"`

This will make it so php.ini and extensions work right out of the box on chocolately.

**Comment by ferventcoder** [comment]
Thanks!

**Comment by oskarlh** [comment]
The php package isn't very useful so long as this issue remains, maybe it should be marked as broken in the meantime?

**Comment by majkinetor** [comment]
> extension_dir = "C:\tools\php\ext"

Does the relative path work: (php.ini): `extension_dir = "ext"`

**Comment by majkinetor** [comment]
Implemented here: https://github.com/chocolatey/chocolatey-coreteampackages/commit/4304f3b78c3d51a16c622a71cbc0fec8434cc6a4

**Comment by oskarlh** [comment]
@majkinetor extension_dir = "ext" works, yes.

**Comment by majkinetor** [comment]
`PHPRC` is not needed then ?

**Comment by oskarlh** [comment]
> PHPRC is not needed then ?
Shouldn't be. From http://php.net/manual/en/configuration.file.php :

>  php.ini is searched for in these locations (in order):
> [...]
> The web server's directory (for SAPI modules), or directory of PHP (otherwise in Windows).

**Comment by laurin1** [comment]
> PHPRC is not needed then ?

That depends on the configuration and there are various factors:

- maintaining separate php.ini files for dev and prod
- location of php.ini files - I guess this installation assumes that php.ini is in the php folder root? (for dev, ours is not, but for prod it is)
- IIS or Apache (it's a lot easier to with IIS if the PHPRC env variable exists)
- web server or command line - with Apache, this is much easier to maintain different configurations (possible with IIS, but not near as easy to manage or switch)

I haven't actually tested this package (we prefer to "install" using the zip file and store the whole thing in a Git repo), but I'll do that right now to see if I can give some more specific input.

**Comment by majkinetor** [comment]
If it works with default location its good enough. All other contexts you specify are too specific for installer and should be part of configuration scripts.

**Comment by gep13** [comment]
This package is now being maintained here:

https://github.com/chocolatey/chocolatey-coreteampackages

So going to close this out.
