### ISSUE TITLE
(paint.net) fails verifier

### ISSUE THREAD

**Issue by dtgm** [ferventcoder/chocolatey-packages#148]
https://chocolatey.org/packages/paint.net/4.0.9
https://gist.github.com/choco-bot/c8c31b8e712990e36eeb
#### Problems
1. Fail is due to confirmation popup that cannot be suppressed. Testing in Win10 shows this popup is not present so it appears to be dependent on install env.
2. Newer versions rely on [dotnet4.6](https://chocolatey.org/packages/DotNet4.6) which is currently failing as well. So `dotnet4.6` needs to also be fixed for this to pass testing.
#### Solution
- [ ] Create an AHK
- [ ] unreject [4.0.9](https://chocolatey.org/packages/paint.net/4.0.9) @ferventcoder @gep13
- [ ] fix dotnet4.6 to work within verifier @jivkok

**Comment by gep13** [comment]
@dtgm I believe that the problems with this package have now been resolved, and are now being maintained in the core team packages repository.
