### ISSUE TITLE
(git.install) Option to install without Credential Manager

### ISSUE THREAD

**Issue by camalot** [ferventcoder/chocolatey-packages#149]
By default, Git for Windows is installing with the Credential Manager. It is also set as the credential helper after install. 

Should have a way to install without the Credential Manager, if so desired.

**Comment by ferventcoder** [comment]
Thanks for logging this!

**Comment by dtgm** [comment]
I don't see the installer currently supporting this. It needs to have support added to be configured from a registry key. File an issue at https://github.com/git-for-windows/build-extra

**Comment by ferventcoder** [comment]
@dtgm I was thinking this could be added as a registry key add. Are you saying that is not possible?

**Comment by ferventcoder** [comment]
Through package parameters like we support all of the other missing silent arguments.

**Comment by dtgm** [comment]
@ferventcoder That is what I am saying. It looks like the installer isn't setup to read a registry key for that option.

**Comment by ferventcoder** [comment]
Not controllable through components either I take it. 👎

**Comment by dtgm** [comment]
Naw, it isn't registered as a component.

**Comment by pascalberger** [comment]
I think this can be closed since it would require upstream implementation in the Git installer. A workaround can be to use the portable version of Git which doesn't contain the Credential Manager.

**Comment by pascalberger** [comment]
I added a PR to the core team packages repository for a separate package which would disable GCM. See https://github.com/chocolatey/chocolatey-coreteampackages/pull/581

**Comment by pascalberger** [comment]
The package is now pushed: https://chocolatey.org/packages/git-disable-gcm

**Comment by medianick** [comment]
@pascalberger, the git-disable-gcm package is useful for the initial install, but only does the unset when it's first installed, whereas the git package sets the credential.helper back to "manager" every time it's updated -- which is often. Unless the plan is to push a new version of git-disable-gcm every time the git package itself gets updated, it seems users have to force a reinstall (choco install git-disable-gcm --force) in order to continue to make use of this.

**Comment by pascalberger** [comment]
@medianick I created https://github.com/chocolatey/chocolatey-coreteampackages/issues/608 for tracking this issue.

And also https://github.com/chocolatey/chocolatey-coreteampackages/issues/606 for adding a paramter to the `git.install` package, which seems now be possible.
