### ISSUE TITLE
(git.install) Git package option to install without the shell integration

### ISSUE THREAD

**Issue by bazzilic** [ferventcoder/chocolatey-packages#151]
Follow up of this discussion: https://chocolatey.org/packages/Git#comment-2728514955

It would be useful to have an option to disable shell integration in the git installer. Probably should even be the default behavior.

**Comment by ferventcoder** [comment]
It was the default behavior - too many folks asked for a closer experience to the what the installer does by default.

**Comment by bazzilic** [comment]
Alright, understood. But is it possible to add a parameter to disable the integration?

**Comment by ferventcoder** [comment]
Yes.

**Comment by xombiemp** [comment]
I'd like this parameter as well.

**Comment by pascalberger** [comment]
Can be closed. Will be implemented with https://github.com/chocolatey/chocolatey-coreteampackages/pull/489
