### ISSUE TITLE
(vagrant) Probably remove dependency in Vagrant 1.8.5

### ISSUE THREAD

**Issue by StefanScherer** [ferventcoder/chocolatey-packages#152]
Just a reminder to remove the [dependency to vcredist2010](https://github.com/ferventcoder/chocolatey-packages/blob/a56aee63316143de8c8c2b67d3d145b29c27a7c0/automatic/vagrant/vagrant.nuspec#L36) for Vagrant 1.8.5 as a fix has been merged into the vagrant-installers repo, [adding the vcredist dll](https://github.com/mitchellh/vagrant-installers/pull/78) inside the embedded bin directory.

**Comment by ferventcoder** [comment]
nice

**Comment by ferventcoder** [comment]
It's an auto package, so it may still be there when 1.8.5 deploys. Let's hope I catch it soon after.

**Comment by gtirloni** [comment]
Getting the same issue on a fresh install of Windows 10 with VirtualBox 5.0.26 and Vagrant 1.8.5.

**Comment by StefanScherer** [comment]
@gtirloni You still have to install the vcredist as my merged PR in the vagrant installers repo didn't made it into the 1.8.5 release.

**Comment by gtirloni** [comment]
@StefanScherer ah, that makes sense. Thanks for the heads up!

**Comment by StefanScherer** [comment]
Just ran a test with Vagrant 1.9.1 MSI https://github.com/mitchellh/vagrant/issues/7637#issuecomment-265949755 and it now has the missing runtime dll in the embedded folder. So the dependency could be removed as it is no longer needed.

**Comment by majkinetor** [comment]
This is fixed with migration to core team packages.

**Comment by StefanScherer** [comment]
Thank you

**Comment by majkinetor** [comment]
Keep in mind that it will be pushed with next vagrant version.
