### ISSUE TITLE
(virtualbox) update and running VMs

### ISSUE THREAD

**Issue by bazzilic** [ferventcoder/chocolatey-packages#153]
Apparently, the Virtualbox installer does not handle running VMs well and just aborts them when updates the installation, which is not cool. It is possible to do graceful shutdown using a combination of `VBoxManage list runningvms` and `VBoxManage controlvm <vm id> acpipowerbutton`. Could that be incorporated into the chocolateyInstall.ps1 for Virtualbox?

This probably should be handled by the installer itself but chances to reach Oracle on that are slim.

**Comment by ferventcoder** [comment]
You mean something for chocolateyBeforeModify.ps1? Like shutting down before upgrade or uninstall?

**Comment by bazzilic** [comment]
I wasn't aware of chocolateyBeforeModify.ps1 but I think yes.

**Comment by ferventcoder** [comment]
Brand new for 0.9.10.x - allows shutting down services and ensuring files are not running before upgrade/uninstall.

**Comment by ferventcoder** [comment]
@majkinetor @admiringworm - one to add to your list of requests.

**Comment by gep13** [comment]
@majkinetor has this issue been resolved?

**Comment by majkinetor** [comment]
yes
