### ISSUE TITLE
Vagrant 1.7.4 broken due to old download link

### ISSUE THREAD

**Issue by StefanScherer** [ferventcoder/chocolatey-packages#178]
On some of my machines I'm forced to use Vagrant 1.7.x, (latest is 1.7.4) instead of 1.8.x.

But provisioning machines with chocolatey does no longer work with

```
choco install vagrant -version 1.7.4
```

as the download link schema has changed (choco package now use the new ones with [this commit](https://github.com/ferventcoder/chocolatey-packages/commit/54c05270cfb46b0730832382b0eb928743ea2a77)) and in the meantime Hashicorp has removed the old download links.

Is it possible to have a fixed choco package 1.7.4.currentdate to have that new download link to retrieve the vagrant 1.7.4 msi file again?

**Comment by ferventcoder** [comment]
Yeah, we need to update all of the old ones to the new url. They moved all of them with a promise to not move them again.

**Comment by StefanScherer** [comment]
Anything I can help to make this happen?

**Comment by ferventcoder** [comment]
Yes! 👍 

In the `automatic/_output/vagrant` folders, you will find different versions. Those will need an update for the fix, plus the packagefix version notation added at the end.

**Comment by ferventcoder** [comment]
Thanks so much for the help sir!

**Comment by StefanScherer** [comment]
Thank you for the fast merge!

**Comment by StefanScherer** [comment]
Approved!

```
choco install vagrant -version 1.7.4.20160919
```
