### ISSUE TITLE
Move packages from this repo to the core team packages repo

### ISSUE THREAD

**Issue by TomOne** [ferventcoder/chocolatey-packages#18]
I know that you’ve planned to move your packages to the core team repo some time ago.

Now it would be a good opportunity to do that. You’ve merged my bunch of PRs in this repo and there are currently only [2 PRs left](https://github.com/ferventcoder/chocolatey-packages/pulls).

Therefore I suggest to move your packages to the core team packages repo as soon as possible before the number of PRs in this repo increases.

These are the steps I would suggest:
- [ ] Add your current repo as branch of the chocolatey-coreteampackages repo, which can be merged to master aftwards.
- [ ] Update the deprecation notes of https://github.com/ferventcoder/nugetpackages and https://github.com/ferventcoder/chocolateyautomaticpackages, add a deprecation note to this repo and make them point to https://github.com/chocolatey/chocolatey-coreteampackages as the new repo.
- [ ] Update the link to the packages repository of your profile site on chocolatey.org.
- [ ] Remove the package files from this repo (except the icons) to prevent confusion and duplicate package source files.

Afterwards there are necessary some a bit more laborious steps. If you want, I can handle these for you, so that you would only have to accomplish the steps above which only take a couple of minutes.

These are the following steps I would do:
- Add the chocolatey user as maintainer of all packages in this repository.
- Normalize package files (e.g. converting nuspecs to UTF-8)
- Deduplicate package icons
- Adapt the package’s iconUrls to use cdn.rawgit.com.
- Import all Ketarin jobs into the Ketarin instance on the server.
- Merge the branch you’ve created into master.
- Adapt the packages that include binaries to download the binaries instead and include them into the built package using the `ChocoPkgUp.ps1`. The [yumi](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/yumi) package does that already for example. A bloated core team packages repository with a lot of binaries is not reasonable.

**Comment by ferventcoder** [comment]
Closing this as this is actually happening now.
