### ISSUE TITLE
(7zip.install) Add a proper uninstall option to 7zip

### ISSUE THREAD

**Issue by scowalt** [ferventcoder/chocolatey-packages#188]
Currently, `choco uninstall 7zip` will remove the 7zip and 7zip.install packages, but won't actually uninstall the program.

It would be great to improve the package, such that the uninstaller for the program runs when the package is removed.

**Comment by ferventcoder** [comment]
This was migrated over to the community team repository and it looks like they have added an uninstall script. HTH
