### ISSUE TITLE
(git.install) Git menu items are missing their icon

### ISSUE THREAD

**Issue by kenny-evitt** [ferventcoder/chocolatey-packages#189]
The two Explorer { context menu / shell integration } items are missing their icon (as I'm pretty sure they use the same icon), as well as are _Git Bash_, _Git GUI_, and _Git CMD_ Start menu items.

All of the above shortcuts seem to expect the icon file _%SystemDrive%\Program Files\Git\mingw64\share\git\git-for-windows.ico_.

I checked a 'manual' install (via the installer) on another computer and that file exists. That install was for a previous but still recent version (2.9.2).

Copying the missing file manually unfortunately doesn't fix the icon displayed in the Explorer context menu or in the Start menu. I suspect it might be fixed automagically at some point, e.g. when Windows refreshes its cached version of the icons for those items.

I'm willing to look into this myself if someone could provide some direction on how best to do so. Maybe the first thing to check should be whether this problem occurs for a 'manual' install of the same version.

**Comment by espoelstra** [comment]
@kenny-evitt If you could do a manual install via the msi or exe and report whether the issue occurs when installing from the native installer it would definitely help lead which direction to start troubleshooting.

**Comment by kenny-evitt** [comment]
@espoelstra Apparently something fixed this as none of the menu items, in either the Start menu or the Explorer context menu, are now missing icons on my computer. I'd guess Windows refreshed the icon cache for the items, but I can't remember now when that might have happened.

I checked my notes but I didn't record anything beyond what I included in my original comment so the only thing I know I did for sure was to copy the *git-for-windows.ico* file. As I didn't note that I deleted that file, I'm assuming I didn't delete it.

There doesn't seem to be much utility in keeping this issue open now.

**Comment by dragon788** [comment]
Closing it makes sense. Sometimes a reboot or explorer.exe restart (or crash) will refresh the icon cache. Other times just installing another package that triggers a reload of explorer.exe can fix this as well, Clover the alternative file browser for Windows is one example that comes to mind.
