### ISSUE TITLE
(ruby) Ruby has outdated RubyGems version

### ISSUE THREAD

**Issue by liamdawson** [ferventcoder/chocolatey-packages#194]
I had to follow the instructions at http://guides.rubygems.org/ssl-certificate-update/ to download any gems. Maybe this could be built into the install process?

**Comment by ferventcoder** [comment]
For what versions of Ruby? We've known about some of the older ones needing something, but not newer versions. Someone was planning to do that about this time last year but then I unfortunately we never saw the PR.

**Comment by liamdawson** [comment]
I installed 2.3.1 and the dev kit and encountered this issue.

**Comment by ferventcoder** [comment]
Nevermind, This was the new SSL cert that requires a newer gems version.

**Comment by ferventcoder** [comment]
Related to #57

**Comment by KakersUK** [comment]
Any chance of updating the Ruby package to 2.3.3? At the moment you can't do anything with rubygems using the chocolatey package:

```
PS C:\Windows\system32> gem install sass
ERROR:  Could not find a valid gem 'sass' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

PS C:\Windows\system32> gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
```
