### ISSUE TITLE
(7zip.install) package won't install due to no https and no checksum

### ISSUE THREAD

**Issue by hvindin** [ferventcoder/chocolatey-packages#198]
Installing the 7zip package seems to fail because there is neither an checksum nor a HTTPS URL.

The errors about this could just be a red herring but it seems to work if I manually add an HTTPS URL.

I'll open a PR in a little bit for the 7zip.install package, frustratingly 7zip.org doesn't support HTTPS and there doesn't seem to be a checksum file published nor is it simple to retrieve a checksum from Sourceforge programmatically.

It's a bit of a hack but you can just use the sourceforge download urls to get the HTTPS support which lets current versions of chocolatey install the package without complaining. Sadly the 7z commandline versions of 7zip aren't available from sourceforge so they are stuck with http and no checksums

**Comment by ferventcoder** [comment]
7zip has been migrated over to the core community team repository where it can be better triaged by a group of folks instead - with everything else related to Chocolatey on my plate I don't get into managing packages as often as I would like. HTH
