### ISSUE TITLE
(Windirstat) error 404 can't find installer file

### ISSUE THREAD

**Issue by dashrender** [ferventcoder/chocolatey-packages#210]
Reporting that Windirstat had issues.

Though looks like it's been fixed today.  Will confirm tomorrow.

**Comment by dashrender** [comment]
windirstat v1.1.2.20160811 [Approved]
windirstat package files upgrade completed. Performing other installation steps.
Attempt to get headers for http://download01.windirstat.info/wds_current_setup.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://download01.windirstat.info/wds_current_setup.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading windirstat
  from 'http://download01.windirstat.info/wds_current_setup.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://download01.windirstat.info/wds_current_setup.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The upgrade of windirstat was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\windirstat\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - windirstat (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\windirstat\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by ferventcoder** [comment]
Just pushed https://chocolatey.org/packages/windirstat/1.1.2.20161210. Once approved, it will never 404 again - license was embed friendly.
