### ISSUE TITLE
(citrix-receiver) please update to v 4.5

### ISSUE THREAD

**Issue by dashrender** [ferventcoder/chocolatey-packages#211]
I'm not sure how this works, but Citrix has updated the file at the download location used.  The package is unaware that an update is there, so it won't download it.

But, if you uninstall citrix-receiver and reinstall it, it will install V4.5, but choco will report that 4.4 is installed.

**Comment by ferventcoder** [comment]
Howdy, what brought you to this repository? I don't maintain the citrix receiver (that I know of).

**Comment by ferventcoder** [comment]
https://chocolatey.org/packages/citrix-receiver ?

Looks like you should head there and in the menu on the left, use the contact maintainers link. Note there is also a link to a Possible Package Source where you can also report the issue and possibly file a pull request (PR) to get it fixed. HTH.

**Comment by ferventcoder** [comment]
Marked as invalid as this issue doesn't apply to this repo. Try over at https://github.com/iainbrighton/Chocolatey-Packages
