### ISSUE TITLE
Update Skype to 7.30.80.105 

### ISSUE THREAD

**Issue by fraenki** [ferventcoder/chocolatey-packages#227]
The version of Skype which is available from the choco repository (7.29.0.102) seems to cause many crashes (on Windows 10). Please update it to the latest release 7.30.80.105 .

**Comment by ferventcoder** [comment]
Thanks for the note. Looking to upgrade this package quite soon.

**Comment by gep13** [comment]
This package is now being maintained here:

https://github.com/chocolatey/chocolatey-coreteampackages

So going to close this out.
