### ISSUE TITLE
Cream vim fails download

### ISSUE THREAD

**Issue by switchspan** [ferventcoder/chocolatey-packages#234]
When I run `choco install vim` it fails with the following Error: "The remote file either doesn't exist, is unauthorized, or is forbidden. See attached screen capture.
![2017-03-06_14-11-22](https://cloud.githubusercontent.com/assets/529598/23625433/27401238-0277-11e7-8c85-210a0fd9d1c2.png)

**Comment by ferventcoder** [comment]
Thanks for noting this. Apologies on slow response on this repo - many things tend to grab my attention as far as Chocolatey goes. We are in the process of migrating packages I've been maintaining over to the core community team repository where they can be triaged and better managed for updates. HTH

**Comment by ferventcoder** [comment]
The last download of the cream installer seems to be green for the community repo - https://chocolatey.org/packages/vim

That green ball in the title is a link to https://gist.github.com/choco-bot/47e9ad74f0aa4858bad04f69218d0a96
