### ISSUE TITLE
Please update Dropbox package

### ISSUE THREAD

**Issue by pyhedgehog** [ferventcoder/chocolatey-packages#236]
Current "real" dropbox version is [21.4.25](https://schd.io/XMe).
Current version of dropbox package is [16.4.30](https://chocolatey.org/packages/dropbox).

**Comment by gep13** [comment]
@pyhedgehog I believe I am correct in saying that this has been taken care of.

Please let me know if you have any questions.

**Comment by pyhedgehog** [comment]
Thank you.
