### ISSUE TITLE
Ruby 2.3.4 and 2.4.1 released

### ISSUE THREAD

**Issue by MartyGentillon** [ferventcoder/chocolatey-packages#242]
In March, the newest versions of Ruby were released, but this hasn't been updated yet.

https://www.ruby-lang.org/en/

Old commit updating to 2.3.3 hasn't made it in yet: https://github.com/ferventcoder/chocolatey-packages/pull/238.

**Comment by ferventcoder** [comment]
@MartyGentillon We have to wait for the Ruby installer folks to get Windows builds of those releases. As you can see from https://bintray.com/oneclick/rubyinstaller/rubyinstaller and https://rubyinstaller.org/downloads/, that has not happened yet. HTH
