### ISSUE TITLE
(nodejs) No nodejs.portable

### ISSUE THREAD

**Issue by SamuelEnglard** [ferventcoder/chocolatey-packages#244]
Any reason there is no nodejs.portable?

**Comment by ferventcoder** [comment]
Hi @SamuelEnglard - there is a nodejs.commandline (which is the same). However I'd completely caution against it as it did not include npm (the package takes a dependency on that though) and the NodeJS folks stopped keeping NPM updated outside of the NodeJS installer. So while you can get a portable NodeJS up and going, you will only have a very old version of NPM that doesn't work very well on Windows.

Grain of salt - this is the last status I knew, but things could have changed.

**Comment by ferventcoder** [comment]
@SamuelEnglard a heads up based on a comment I saw - not all portable packages have ".portable" in the name. Like sysinternals - if it had portable it would be harder to guess at install time. Typically ".portable" is reserved for when there is both an installer and an archive (zip) of the software binaries being offered. HTH

**Comment by SamuelEnglard** [comment]
I think that comment is from me that you're referencing 😂 

I did see the nodejs.commandline package but was wary of it because of the reasons you stated. I'm trying to remove all "installers" from my machine unless needed but if I have no choice here I'll stick with the installer.

Thanks!

**Comment by ferventcoder** [comment]
@SamuelEnglard that's a good idea - have you seen this as well? https://gist.github.com/ferventcoder/78fa6b6f4d6e2b12c89680cbc0daec78

**Comment by SamuelEnglard** [comment]
That's exactly what I'm trying to do!
