### ISSUE TITLE
(mysql) Visual C++ Redistributable Packages for Visual Studio 2013 should be part of the dependencies

### ISSUE THREAD

**Issue by aemery** [ferventcoder/chocolatey-packages#253]
vcredist2013 should be part of the dependencies of the MySQL package.

Without the vcredist2013 install, choco install mysql will report "The install of mysql was successful." but with Get-Service you can see that the MySQL service is not installed. Running "choco install vcredist2013" before installing the MySQL fixes the problem.

I am able to reproduce easily from a vanilla Windows Server Core Docker (docker pull microsoft/windowsservercore).

**Comment by ferventcoder** [comment]
This was added, but the package has not had a release that would push this out yet.
