### ISSUE TITLE
Possible to update 1Password to version 6.7?

### ISSUE THREAD

**Issue by luislavena** [ferventcoder/chocolatey-packages#256]
Hello!

Thank you for creating Chocolatey packages for 1Password!

I was wondering if will be possible (and how) to update 1Password to latest version (6.7.454) instead of the standalone one (v4)

Took a look but seems this particular package is build automatically, so not sure how that is done (compare to other manually updated packages)

Thank you for your time and for working on this package! (and chocolatey itself!)
❤️ ❤️ ❤️

**Comment by ferventcoder** [comment]
Hi @luislavena! I didn't realize 1Password was up to 6.x, although I probably should have considering it is that high on other platforms!

**Comment by gep13** [comment]
@AdmiringWorm yip, looks like the issue was correctly closed 😄
