### ISSUE TITLE
GitExtensions - Not Updating Automatically (2.50.01)

### ISSUE THREAD

**Issue by laurin1** [ferventcoder/chocolatey-packages#257]
Version 2.50.01 has been out since 7/7/17. Per our conversation in Gitter:

> Rob Reynolds @ferventcoder Jul 27 10:49
> Ha, I have switched over to AU - still on old method.

So I guess it's still not working?

**Comment by rgl** [comment]
Any news about this @ferventcoder?

**Comment by laurin1** [comment]
2.50.02 has been out for a while now.

**Comment by rgl** [comment]
Any news about updating this package to 2.51.01? Is there anything I can do to speed this up?

**Comment by rgl** [comment]
Oh there is at https://github.com/chocolatey/chocolatey-coreteampackages/issues/900 ... I will submit a manual package there!

**Comment by gep13** [comment]
This is now being maintained over here:

https://github.com/chocolatey/chocolatey-coreteampackages

So going to close this out.

**Comment by laurin1** [comment]
It is? I just looked all over that repo and I don't see it. Am I blind?

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/pull/1023

**Comment by gep13** [comment]
@laurin1 it is in the final stages of getting approved.  Removing the source ketarin files from this repository (so as to avoid any duplication of package creation) was really the last step in getting it merged in.

**Comment by laurin1** [comment]
Thanks.
