### ISSUE TITLE
git package: add package parameter for WinSSL

### ISSUE THREAD

**Issue by mawl** [ferventcoder/chocolatey-packages#269]
Hi,

Can you please add a package parameter for https://chocolatey.org/packages/git to enable "Use the native Windows SChannel library" (WinSSL).  see: https://github.com/git-for-windows/build-extra/pull/135/files 

Thanks a lot :)
Marco

**Comment by ferventcoder** [comment]
Hi @mawl - wrong repository. Now this is located at https://github.com/chocolatey/chocolatey-coreteampackages. You may wish to file this there. Thanks!
