### ISSUE TITLE
Correct packages with misleading and confusing package ID suffixes

### ISSUE THREAD

**Issue by TomOne** [ferventcoder/chocolatey-packages#27]
I already mentioned this here: https://github.com/ferventcoder/chocolatey-packages/pull/2#issuecomment-50519299

How about doing this with the packages that are in your repo? There are not too many of them and renaming them correctly would make the gallery a bit less confusing.

Especially the `.commandline` suffix is often complete nonsense, e.g. https://chocolatey.org/packages/notepadplusplus.commandline. Sounds like vim for the Windows ecosystem. :smile:

https://chocolatey.org/packages/sumatrapdf.commandline sounds like a PDF Viewer for the command line. :smile: 

Keep in mind that in package repositories it is not uncommon to rename/deprecate packages, so I think tidying up and correct package names wouldn’t be a bad thing.

**Comment by ferventcoder** [comment]
This will eventually get picked back up in the core team repo.
