### ISSUE TITLE
Toggl hasn't been pushed in 2 years

### ISSUE THREAD

**Issue by Zenexer** [ferventcoder/chocolatey-packages#295]
The version of Toggl in this repo is much newer than the version in the Chocolatey repos.

**Comment by gep13** [comment]
@Zenexer The Toggl package in this repository is a manually updated package:

https://github.com/ferventcoder/chocolatey-packages/tree/master/manual/toggl

If you are in a position to update it to the latest download URL's etc, I can get it pushed out.

**Comment by Zenexer** [comment]
@gep13 afaict, the package in the repo is significantly newer than the package on the Chcoolatey repos.  That's a separate issue from the package in the repo being out of date.

**Comment by Zenexer** [comment]
https://github.com/ferventcoder/chocolatey-packages/tree/master/manual/toggl says 7.4.18, but https://chocolatey.org/packages/toggl says 7.3.318.

**Comment by gep13** [comment]
@Zenexer A package version for 7.4.18 had been pushed:

https://chocolatey.org/packages/toggl/7.4.18

However, it was rejected via moderation, and it was never updated 😢 

I have just pushed a new version 7.4.252:

https://chocolatey.org/packages/toggl/7.4.252

Which will hopefully go through moderation without any problems this time.
