### ISSUE TITLE
sumatrapdf* new version

### ISSUE THREAD

**Issue by jacktose** [ferventcoder/chocolatey-packages#309]
sumatrapdf (.install, .commandline) package is at 3.1.2. Version 3.2 is out: https://www.sumatrapdfreader.org/docs/Version-history.html
Note: it removes support for Windows XP.

**Comment by TheCakeIsNaOH** [comment]
@jacktose this can be closed, I [updated the package to version 3.2.](https://chocolatey.org/packages/sumatrapdf.install)

**Comment by gep13** [comment]
@TheCakeIsNaOH thanks for confirming!
