### ISSUE TITLE
Git Extensions 2.48 removed git-credential-winstore.

### ISSUE THREAD

**Issue by jnsn** [ferventcoder/chocolatey-packages#31]
After updating Git Extensions to 2.48 the following error is shown:

```
"C:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe" get:
C:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe: No such file or directory
```

Since version 2.48 it seems the _git-credential-winstore.exe_ file is only available from the Complete installer, as noted on https://github.com/gitextensions/gitextensions/issues/1492#issuecomment-59915231.

My initial guess would be that the Chocolatey package should use the Complete installer, however I can also reason that it would not be desirable in some cases. My guess is that there has been a good reason why this was not used in the past. I also think that it would be dangereous to simply remove the entry from the user's Git config file. Hence, I don't really know how this should be fixed, but at least it should be documented somehow.

**Comment by koppor** [comment]
Since (at least) git for windows v2.8.2, the [git credential manager is shipped with git](https://github.com/git-for-windows/git/releases/tag/v2.8.2.windows.1). Thus, there shouldn't be any need to package it separately.

**Comment by ferventcoder** [comment]
I don't know if this is still an issue. If this is, please feel free to comment and I will reopen this.
