### ISSUE TITLE
404 webpicmd download urls

### ISSUE THREAD

**Issue by cristiano2lopes** [ferventcoder/chocolatey-packages#317]
Both urls specified here are returning 404 as of today 2020-08-06.  

https://github.com/ferventcoder/chocolatey-packages/blob/da409183f9e3459668a0056c69d952edfd50e158/manual/webpicmd/tools/chocolateyInstall.ps1#L5
https://github.com/ferventcoder/chocolatey-packages/blob/da409183f9e3459668a0056c69d952edfd50e158/manual/webpicmd/tools/chocolateyInstall.ps1#L6

Probably Microsoft doing Microsoft things, but I will leave it here in case it's not temporary. Same links also broken at https://docs.microsoft.com/en-us/iis/install/web-platform-installer/web-platform-installer-direct-downloads.

**Comment by ferventcoder** [comment]
Hmmm. Wonder if they've removed WebPI?

**Comment by ferventcoder** [comment]
https://www.microsoft.com/web/downloads/platform.aspx. Looks like maybe they moved them?

**Comment by ferventcoder** [comment]
Actually, the links appear to be working for me. Maybe something was temporarily down?
