### ISSUE TITLE
kdiff3 is old in chocolatey/is this the right repo

### ISSUE THREAD

**Issue by Cyber1000** [ferventcoder/chocolatey-packages#337]
https://community.chocolatey.org/packages/kdiff3 says this is the "possible source repo" for kdiff3. But actually I've found only an icon here in this repo.

The point is: Is kdiff3 maintained through this repo? If yes, there is a version 1.9.5 already (in chocolatey 0.9.98), is it possible to update this? If no can you point me to the right repo of the package maintainer?

Thanks!

**Comment by gep13** [comment]
@Cyber1000 no, this package is not maintained here in this repository.  The kdiff3 package was actually just updated to replace deprecated functions by a new maintainer md97.

My suggestion would be to reach out to them to see if they are in a position to update it.

However, looking at the site:

http://kdiff3.sourceforge.net/

It does appear that this is still the latest version, unless it is now hosted on another site.

**Comment by jnsn** [comment]
> https://community.chocolatey.org/packages/kdiff3 says this is the "possible source repo" for kdiff3. But actually I've found only an icon here in this repo.
> 
> The point is: Is kdiff3 maintained through this repo? If yes, there is a version 1.9.5 already (in chocolatey 0.9.98), is it possible to update this? If no can you point me to the right repo of the package maintainer?
> 
> Thanks!

The info is located in https://github.com/ferventcoder/chocolatey-packages/tree/master/manual/kdiff3.

> @Cyber1000 no, this package is not maintained here in this repository. The kdiff3 package was actually just updated to replace deprecated functions by a new maintainer md97.
> 
> My suggestion would be to reach out to them to see if they are in a position to update it.
> 
> However, looking at the site:
> 
> http://kdiff3.sourceforge.net/
> 
> It does appear that this is still the latest version, unless it is now hosted on another site.

kdiff3 migrated away from the SF website a long time ago, and it's new home has been https://invent.kde.org/sdk/kdiff3 for at least a few years now. The latest release is 1.9.5 as per https://download.kde.org/stable/kdiff3/.

**Comment by Cyber1000** [comment]
> The info is located in https://github.com/ferventcoder/chocolatey-packages/tree/master/manual/kdiff3

@jnsn I get a 404 on this link

And you are right kdiff is version 1.9.5. 

I just came from https://community.chocolatey.org/packages/kdiff3 and it says package maintainer "ferventcoder" (and others), so I thought this github-repo must match.

**Comment by jnsn** [comment]
> @jnsn I get a 404 on this link

It has been removed since I mentioned it: https://github.com/ferventcoder/chocolatey-packages/commit/d2c2489c98a47613f1490fae13d1dd2c120eaa72
