### ISSUE TITLE
(php) PHP doesn't respect proxy calls when it checks for existence versus archive

### ISSUE THREAD

**Issue by ferventcoder** [ferventcoder/chocolatey-packages#38]
When the PHP package checks to see if the original download location exists, it doesn't check to see if a proxy is present, thus resulting in it switching to the archive folder, which may not exist.

The offending code is https://github.com/ferventcoder/chocolatey-packages/blob/master/automatic/php/tools/chocolateyInstall.ps1#L1-L12

**Comment by majkinetor** [comment]
This would ideally require to abstract the proxy section from `Get-WebFile` and friends into reusable component. This type of proxy question is relatively frequent and should be solved systematically.

**Comment by ferventcoder** [comment]
@majkinetor yes it is. Yes it should.

**Comment by ferventcoder** [comment]
Closed by work going on in coreteam packaging.
