### ISSUE TITLE
Fix php package

### ISSUE THREAD

**Issue by TomOne** [ferventcoder/chocolatey-packages#53]
Shouldn’t the php package put the bin folder onto PATH?

After installing this package on a fresh W8 VM, attempting to launch php.exe failed: “MSVCR110.dll is missing”. Perhaps this needs the ms c++ runtimes as dependency?

**Comment by TomOne** [comment]
Doesn’t php `$env:ProgramFiles\php` by default? Is there a reason to choose another directory?

**Comment by ferventcoder** [comment]
No idea on default - there was a path it used to install to - but maybe that has changed more recently.

**Comment by ferventcoder** [comment]
From a recent email:
"php requires vcredist2015 to run, I think it should be in the dependencies"

**Comment by ferventcoder** [comment]
I'm not sure this is still an issue. If so this can be reopened later.
