### ISSUE TITLE
(putty) Use version-specific download links for putty

### ISSUE THREAD

**Issue by TomOne** [ferventcoder/chocolatey-packages#55]
Currently the putty packages always download the latest version, regardless which version an user chooses to install. It should use the version-specific links instead, e.g. http://the.earth.li/~sgtatham/putty/0.64/x86/putty-0.64-installer.exe

They are more conform with package managers and don’t break checksum comparision when the version is updated on the server, but not in the package.

**Comment by ferventcoder** [comment]
Agreed. Not as easy to find though.

**Comment by ferventcoder** [comment]
And is that a preview or the release? That's alway hard to know

**Comment by TomOne** [comment]
As long there’s no -alpha, -beta, or -pre stuff added to the version, it is not a prerelease version. That’s my definition of it. :smiley_cat:

**Comment by TomOne** [comment]
Actually putty is beta software. From the [website](http://www.chiark.greenend.org.uk/~sgtatham/putty/):

> The latest version is beta 0.64.

But does that matter?

**Comment by ferventcoder** [comment]
Ah, i got confused because he/she just put it in preview last week and I
updated it to that.

This is an actual release.

On Monday, March 2, 2015, TomOne <notifications@github.com> wrote:

> Actually putty is beta software. From the website
> <http://www.chiark.greenend.org.uk/%7Esgtatham/putty/>:
>
> The latest version is beta 0.64.
>
> But does that matter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ferventcoder/chocolatey-packages/issues/55#issuecomment-76860856>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by pascalberger** [comment]
This would be fixed with https://github.com/chocolatey/chocolatey-coreteampackages/pull/539, as both `putty.install` and `putty.portable` are changed to embedded packages.

**Comment by gep13** [comment]
This package is now being maintained here:

https://github.com/chocolatey/chocolatey-coreteampackages

So going to close this out.
