### ISSUE TITLE
Create issue when a Ketarin 404 is detected

### ISSUE THREAD

**Issue by DanAtkinson** [ferventcoder/chocolatey-packages#77]
When Ketarin encounters a 404 error, a GitHub issue should be raised as this would indicate that the package is no longer valid.

I understand from conversations with Gary on the choco gitter that an Azure VM kicks off a scheduled task which determines whether the packages require updates and actions them accordingly.

I gather that this would require scraping the log file in order to determine whether it's failed.

This should look something like the following (for VLC).

> vlc: Failed, The remote name could not be resolved

**Comment by ferventcoder** [comment]
That would be awesome. :)

**Comment by ferventcoder** [comment]
Moving things to AU now that it does a much better job of this.
