### ISSUE TITLE
Packages from this repo no longer updating

### ISSUE THREAD

**Issue by TomOne** [ferventcoder/chocolatey-packages#83]
There seems to be something wrong with your automatic package pushing instance. Since 4 days, new versions of your packages no longer get pushed to chocolatey.org, e.g. virtualbox 5.0, which was released 3 days ago. I tested the ketarin job, but it worked fine, so there must be another issue.

Thanks for looking into it.

**Comment by ferventcoder** [comment]
Thanks for the heads up - will take a look at the machine in a few minutes...

**Comment by ferventcoder** [comment]
It's running now manually - will investigate the sched task

**Comment by ferventcoder** [comment]
I moved the configuration to a cloud box. Also, I think you are going to like this - 

https://github.com/ferventcoder/chocolatey-packages/blob/dff9e8bdd08ba49a6f35aa39a85d45f2a45fe647/ketarin/files/ketarinupdate.cmd#L9-L11

Automatically imports all of the ketarin file updates.

**Comment by ferventcoder** [comment]
@dtgm ^^
