### ISSUE TITLE
Install script for ruby2.devkit getting errors

### ISSUE THREAD

**Issue by cmhamm** [ferventcoder/chocolatey-packages#87]
Attempting to install ruby2.devkit and getting the following error:
 C:\tools\ruby21\bin\ruby.exe: No such file or directory -- dk.rb (LoadError)
 C:\tools\ruby21\bin\ruby.exe: No such file or directory -- dk.rb (LoadError)

I haven't quite wrapped my head around the entire Chocolatey code, but I believe maybe lines 89-91 are causing the script to cd into "$env:systemdrive\DevKit2", whereas Chocolatey is installing the tools into "$env:systemdrive\tools\DevKit2." Not really completely sure that's the case, but it seems clear from the log that dk.rb isn't being found by Ruby, yet it is most definitely in "c:\tools\DevKit2"

I'll continue to research. Maybe I can fix it, once I understand everything that's going on.

**Comment by cmhamm** [comment]
Nope, I think I was wrong. $devKitInstallDir does seem to be pointed at $env:systemroot\tools, which makes line 89 correct.

However, looking over the script running order, it looks like it cleans out the contents of that folder, then downloads and extracts from 'http://cdn.rubyinstaller.org/archives/devkits/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe'

Running and monitoring the installer, it looks like it's trying to run lines 90-91 before the other process has had a chance to re-download the archive that contains dk.rb.

Again, not fully understanding the entire Chocolatey process, is there a way to ensure that download has completed before running lines 90-91?

**Comment by ferventcoder** [comment]
@cmhamm perhaps you can help by specifically linking to the line numbers? https://github.com/ferventcoder/chocolatey-packages/blob/master/manual/ruby2.devkit/tools/chocolateyInstall.ps1#L67-L91

As in what process has had a change to redownload the archive?

**Comment by cmhamm** [comment]
Line 67 is "Start-Process "7za" -ArgumentList "x -o`"$devKitInstallDir`" -y `"$file`"" -Wait"

It looks like, at least on my machine, it's not waiting. I'm getting an admin prompt, I believe for the 7z executable, and it goes right onto the next process. I'm going to try to debug chocolatey...

**Comment by cmhamm** [comment]
Sorry - I have lots of experience in IT, but I am not a seasoned coder... Never even knew that line numbers could be linked.

I'm not sure what you're asking about what process has had a change. When I run the chocolatey installer, it tries to clear out the DevKit2 folder each time the installer script is run. It does successfully re-extract the archive after it runs, but it's definitely not waiting for the Start-Process to complete before moving on.

On my system, adding -NoNewWindow to the end of the [Start-Process cmdlet](https://github.com/ferventcoder/chocolatey-packages/blob/master/manual/ruby2.devkit/tools/chocolateyInstall.ps1#L67) seems to make it behave properly. What I'm not completely sure about is whether or not that would cause other problems in the script.

**Comment by cmhamm** [comment]
I don't know how to properly test the installer if I changed [line 67](https://github.com/ferventcoder/chocolatey-packages/blob/master/manual/ruby2.devkit/tools/chocolateyInstall.ps1#L67) to:
`Start-Process "7za" -ArgumentList "x -o\`"$devKitInstallDir\`" -y \`"$file\`"" -Wait -NoNewWindow`

but I think that would resolve at least my problem. Also there are two other reports that I could find on the Internet of people having the same error. It's possible that it's because of one of the thousands of things I've done to my computer. :smile:

**Comment by ferventcoder** [comment]
PowerShell v3?

**Comment by cmhamm** [comment]
I'm using PowerShell v.5 on Windows 8.1.

**Comment by ferventcoder** [comment]
Weird that the no wait bug is back. It was in POSH v3 as well. See https://github.com/chocolatey/chocolatey/pull/516 for details.

**Comment by cmhamm** [comment]
I can't say for certain that it is the exact same bug, but it is the same behavior. Worth noting, though, that I did try running Chocolatey from within a PowerShell window vs. running from a command window, and it still did not work correctly.

**Comment by thj-dk** [comment]
I'm having the same problem on Windows 10. Did you solve it?

**Comment by falken** [comment]
Still having this problem when launching from Ansible. Has there been any progress?

**Comment by ferventcoder** [comment]
@thj-dk @falken What versions of Chocolatey and PowerShell do you have?

**Comment by falken** [comment]
Chocolatey: 0.9.10.3
Powershell: 3.0
Ansible: 1.9.1

We found that it worked fine if we set the "chocolateyUseWindowsCompression" env variable to true. Otherwise it attempted to run the chocolateyInstall.ps1 file before it was extracted.

**Comment by ferventcoder** [comment]
Now that Choco uses 7z.exe (full) plus we've changed up the code for this in Chocolatey, I'm not sure this is still an issue. If you find it is, please feel free to comment.

@falken If you are still seeing the same issue, please file an issue on https://github.com/chocolatey/choco

**Comment by falken** [comment]
We are still experiencing the problem. It seems to only occur when the choco script is run through ansible. Ansible runs `choco.exe  install -dv -y ruby2.devkit -y --x86 -version 4.7.2.2013022402` which fails to unzip all of the files. When running the command directly on the machine it succeeds. The only difference I can see is that the package is launching a second shell window that runs 7za.exe. I'm not sure why it would need to open a second shell to do that.
