### ISSUE TITLE
Git Install - add package parameter for old bash terminal host

### ISSUE THREAD

**Issue by ferventcoder** [ferventcoder/chocolatey-packages#88]
Inno Setup CodeFile: Bash Terminal Option

the default - mintty (not sure what the registry setting is).
and 
ConHost for equivalent of Git 1.9.5

**Comment by StilgarISCA** [comment]
:+1: for this feature
This change caused me a lot of problems I wasn't expecting to deal with when I upgraded to the latest package.

**Comment by ferventcoder** [comment]
@StilgarISCA crossing a major version boundary (1.x to 2.x) should always be something that you should take closer inspection as that is where breaking changes are known to occur. Just an FYI related to anything with software and versions.

Apologies that this wasn't already in for the 2.x versions of the git package though.

**Comment by jmbeach** [comment]
@ferventcoder Any progress on this? I was on the forms a couple of weeks ago asking about it. The mintty version has caused me a lot of problems.

**Comment by ferventcoder** [comment]
@jmbeach No progress yet. If someone is interested in figuring out the logic, that would be beneficial 👍

**Comment by jmbeach** [comment]
I would do it myself, but I'm not really sure how to get the parameter out of the executable that would change that setting

**Comment by ferventcoder** [comment]
Looks like `Inno Setup CodeFile: Bash Terminal Option` set to `MinTTY` 

![image](https://cloud.githubusercontent.com/assets/63502/17298042/fefe6328-57cd-11e6-899f-5bcdda47c9e2.png)

Would need to install it with the other option to see how that comes across.

**Comment by jmbeach** [comment]
Looks like it is set to `ConHost`
![image](https://cloud.githubusercontent.com/assets/2680142/17300929/2949daf2-57da-11e6-97f9-3ffc33f30041.png)

I will test installing it with that parameter later

**Comment by jmbeach** [comment]
5daf44e

**Comment by ferventcoder** [comment]
Thanks @jmbeach - this should be in the next release of the git install package.
