### ISSUE TITLE
(php) Request for PHP 5.4

### ISSUE THREAD

**Issue by keradus** [ferventcoder/chocolatey-packages#90]
Any chances for PHP 5.4.x ?

**Comment by ferventcoder** [comment]
probably. I take it the auto package is not catching this?

**Comment by keradus** [comment]
Sorry, don't know what auto package is :(
My issue is that 5.4 is not available version on https://chocolatey.org/packages/php

**Comment by ferventcoder** [comment]
5.4 is older. Right on. If you want to put in a PR to add it, I will push it. Thanks!

**Comment by keradus** [comment]
I don't know chocolatey well, I'm afraid that I cannot help with PR.

**Comment by majkinetor** [comment]
There are bunch of php versions missing. Its unrealistic IMO that somebody will do this without some kind of script. That someone would also need to be motivated to have all php versions around.

**Comment by AdmiringWorm** [comment]
I believe this one can be closed.
[v5.4.45](https://chocolatey.org/packages/php/5.4.45) is available on chocolatey.org

/cc @ferventcoder
