### ISSUE TITLE
Git package isn't installing the start menu shortcuts

### ISSUE THREAD

**Issue by bcomnes** [ferventcoder/chocolatey-packages#91]
When I install git with the graphical installer, I get the following start menu shortcuts:

![](https://c2.staticflickr.com/6/5720/21112591254_ac6dc04ca9_o.png)

When I install with chocolaty (`choco install git`) on windows 8.1, these shortcuts are not installed.

Is there a flag I need to pass?  Are they supposed to be installed?

**Comment by ferventcoder** [comment]
The args we pass specifically don't install these shortcuts, but we can add a pkg parameter / preference so they will. Thoughts?

**Comment by bcomnes** [comment]
When I install the git package, I would generally expect these shortcuts to be created by default (similar to how I've seen many other chocolaty packages create start menu shortcuts).  I've seen a couple other packages not create start menu shortcuts when I would expect them to (I think rufus is one of them) and its thrown me for a loop.

Is there some kind of existing raw parameter I can pass when installing git with the current choco git package to get the shortcuts?

Generally though, it would be better if there was some kind of consistent default (when possible): install start menu shortcuts always, or never install them by default (argument flag only).  My preference would be to default to the always install shortcuts option.

**Comment by ferventcoder** [comment]
> Generally though, it would be better if there was some kind of consistent default (when possible): install start menu shortcuts always, or never install them by default (argument flag only). My preference would be to default to the always install shortcuts option.

You touched on both the problem and the solution here. Everyone has a different preference. See/subscribe to https://github.com/chocolatey/choco/issues/344

**Comment by ferventcoder** [comment]
While the package now does this, we likely need to pull it.

**Comment by ferventcoder** [comment]
The reasoning why is linked from https://github.com/ferventcoder/chocolatey-packages/issues/103
