### ISSUE TITLE
Git - Windows explorer integration parameter

### ISSUE THREAD

**Issue by dazinator** [ferventcoder/chocolatey-packages#93]
Having installed this package on a brand new installation of windows 10, it doesn't appear to add in the windows explorer integration for "git bash here" etc. These are options present in the msi installer. Can we expose some parameters to enable the windows explorer integration?

**Comment by ferventcoder** [comment]
Thanks. I think we can do that.

**Comment by petebachant** [comment]
I am missing this feature as well. Isn't Explorer integration default in the installer?

**Comment by ferventcoder** [comment]
@petebachant it is the default in the installer - however the cheetah integration that was/is present that came along with this causes issues when attempting to upgrade, making a silent upgrade impossible. See https://github.com/git-for-windows/git/issues/312 for more information.

**Comment by fabio-porcedda** [comment]
I also would like to be able to install windows explorer integration.

**Comment by disjukr** [comment]
+1

**Comment by petebachant** [comment]
This appears to be fixed on my system.

**Comment by fabio-porcedda** [comment]
x petebachant: What do you mean exactly?
I've installed right now the latest version (git 2.7.2) on Windwos 10, it still doesn't add shell explorer extensions.

**Comment by petebachant** [comment]
I just updated via Chocolatey on Windows 10 yesterday, and I see the context menu in Explorer. I'm not sure when this arose.

**Comment by ferventcoder** [comment]
@fabio-porcedda This is possibly only a Chocolatey issue. I wouldn't comment on the Git for Windows threads unless you know it is specifically broken in the installer.

**Comment by fabio-porcedda** [comment]
Yes, using the official git installer the context menu in explorer is added.

**Comment by fabio-porcedda** [comment]
I think i've found the reason the shell integration isn't installed using chocolatey.
The chocolatey package enable the following components (*1): 
"icons,icons\quicklaunch,ext,ext\reg,ext\reg\shellhere,ext\reg\guihere,assoc,assoc_sh"

So the right components are not included:
https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss

The missing components are:
<<<
Name: ext; Description: Windows Explorer integration; Types: default
Name: ext\shellhere; Description: Git Bash Here; Types: default
Name: ext\guihere;Description: Git GUI Here; Types: default
>>>

Is fine if i do a pull request adding those components?

*1: https://github.com/ferventcoder/chocolatey-packages/blob/master/automatic/git.install/tools/chocolateyInstall.ps1

**Comment by ferventcoder** [comment]
Old names versus new names.

**Comment by ferventcoder** [comment]
Closed by #125.
