### ISSUE TITLE
(nodejs) Make it easy to maintain an LTS install of nodejs

### ISSUE THREAD

**Issue by mikemoate** [ferventcoder/chocolatey-packages#99]
Nodejs now has the concept of an LTS release, this is currently the 4.2.x series of releases. Currently these releases are mixed in with the more recent 5.x releases within the same chocolatey package, making it hard to maintain an LTS release install with chocolatey.

See conversation at https://chocolatey.org/packages/nodejs#comment-2365980358 you had suggested "Perhaps a meta package for LTS that was specifically about certain version restrictions of nodejs?" as a possible approach.

**Comment by ferventcoder** [comment]
It's possible just another package as well.

**Comment by gtirloni** [comment]
A LTS package would be awesome so we don't have to track specific versions every time there is a new release (to avoid installing the latest/current). Thanks a lot for your work.

**Comment by espoelstra** [comment]
Fixed by d4c244f8e613bd05a96d88391e9c86796e3126ba it appears.

**Comment by ferventcoder** [comment]
There is an LTS version, but it gets pushed as simply nodejs packages. This I believe is to install and keep up to date a separate package.

**Comment by jtcmedia** [comment]
I've submitted an LTS version of Node [https://chocolatey.org/packages/nodejs-lts/6.9.2](https://chocolatey.org/packages/nodejs-lts/6.9.2). It hasn't been approved yet but this should solve the issue.

**Comment by dragon788** [comment]
Nice, and you have it ready for AU as well, hopefully they aren't too inconsistent about the version patterns they dub as LTS.

**Comment by jtcmedia** [comment]
Thanks @dragon788 and I hope so too! This package has been approved; this issue can be closed.
